---

- hosts: all
  tasks:
  - name: Create sudo file for admin
    copy:
      dest: "/private/etc/sudoers.d/admin"
      content: |
        %admin ALL=(ALL) NOPASSWD: ALL
    become: yes

- hosts: all
  name: Install Roles
  roles:
    - homebrew
    - ocaml
    - obuilder-fs
    - { role: base-image, user_name: mac1000 }
    - busybox
    - ocluster
  environment: 
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'

