---

- hosts: all
  tasks:
  - name: Check architecture intel
    set_fact: homebrew_prefix="/usr/local"
    when: ansible_architecture == "x86_64"

  - name: Check architecture arm
    set_fact: homebrew_prefix="/opt/homebrew"
    when: ansible_architecture == "arm64"

  - debug:
      var: homebrew_prefix

- hosts: all
  serial: 1
  tasks:

  - name: Stop the ocluster service
    shell: launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/com.tarides.ocluster.worker.plist
    register: launchctl_check
    failed_when: not ( launchctl_check.rc == 134 or launchctl_check.rc == 0 )

  - name: Stop the ocluster service
    shell: launchctl unload /Library/LaunchDaemons/com.tarides.ocluster.worker.plist
    register: launchctl_check
    become: yes
    failed_when: not ( launchctl_check.rc == 134 or launchctl_check.rc == 0 )

  - name: Remove LaunchAgents folder and plist
    become: yes
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/Library/LaunchAgents"

  - name: Unmount {{ homebrew_prefix }} if it is mounted
    become: yes
    mount:
      path: "{{ homebrew_prefix }}"
      state: unmounted

  - name: Unmount /Users/mac1000 if it is mounted
    become: yes
    mount:
      path: /Users/mac1000
      state: unmounted

  - name: Remove state dir
    become: yes
    file:
      state: absent
      path: /var/lib/ocluster-worker

  - name: Remove ocluster.log
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/ocluster.log"

  - name: Remove obuilder-fs
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/obuilder-fs"

  - name: Remove scoreboard
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/scoreboard"

  - name: Remove lib
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/lib"

  - name: Remove ocluster
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/ocluster"

  - name: Remove macos-infra
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/macos-infra"

  - name: Remove zfs
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/zfs"

  - name: Remove opam
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/.opam"

  - name: Create empty folder
    file:
      state: directory
      path: /tmp/obuilder-empty 

  - name: Use rsync to delete everything in {{ homebrew_prefix }}
    shell: rsync -aHq --delete /tmp/obuilder-empty/ "{{ homebrew_prefix }}"
    become: yes

  - name: Use rsync to delete everything in /Volumes/rsync/
    shell: rsync -aHq --delete /tmp/obuilder-empty/ /Volumes/rsync/
    become: yes

  - name: Remove /Volumes/rsync
    file:
      state: absent
      path: /Volumes/rsync
    become: yes


