---

- name: Ensure LaunchAgents folder exists
  file:
    path: "{{ ansible_env.HOME }}/Library/LaunchAgents"
    state: directory

- name: Create plist service file
  template:
    src: com.tarides.ocluster.worker.plist
    dest: "{{ ansible_env.HOME }}/Library/LaunchAgents/com.tarides.ocluster.worker.plist"

- name: Stop ocluster via launchctl
  shell: launchctl unload ~/Library/LaunchAgents/com.tarides.ocluster.worker.plist

- name: Remove ~/ocluster
  file:
    path: "{{ ansible_env.HOME }}/ocluster"
    state: absent

- name: Download the source from GitHub
  git:
    repo: https://github.com/ocurrent/ocluster.git
    dest: "{{ ansible_env.HOME }}/ocluster"
    force: yes

- name: Switch to Tim's PR
  shell: git fetch origin pull/202/head:test-branch && git checkout test-branch
  args:
    chdir: "{{ ansible_env.HOME }}/ocluster"

- name: Update Obuilder
  shell: git fetch && git checkout master
  args:
    chdir: "{{ ansible_env.HOME }}/ocluster/obuilder"

- name: Update Fetcher variable to User_temp
  replace:
    path: "{{ ansible_env.HOME }}/ocluster/worker/obuilder_build.ml"
    regexp: '^module Fetcher = Obuilder.Docker$'
    replace: 'module Fetcher = Obuilder.User_temp'

- name: Install Opam dependencies
  shell: eval $(opam env) && opam update && opam install dune fmt prometheus-app extunix capnp-rpc-unix digestif psq ppx_expect dune-build-info alcotest-lwt sqlite3 sha current_web lwt-dllist current_git tar-unix current_github -y --confirm-level=unsafe-yes
  args:
    chdir: "{{ ansible_env.HOME }}/ocluster"

- name: Dune build
  shell: eval $(opam env) && dune build
  args:
    chdir: "{{ ansible_env.HOME }}/ocluster"

- name: Copy pool capability
  copy:
    src: "secrets/pool-macos-{{ ansible_architecture }}.cap"
    dest: "{{ ansible_env.HOME }}/pool-macos-{{ ansible_architecture }}.cap"
    mode: '0400'

- name: Ensure ~/lib exists
  file:
    path: "{{ ansible_env.HOME }}/lib"
    state: directory

- name: Start ocluster via launchctl
  shell: launchctl load ~/Library/LaunchAgents/com.tarides.ocluster.worker.plist

