---

- name: Ensure LaunchAgents folder exists
  file:
    path: "{{ ansible_env.HOME }}/Library/LaunchAgents"
    state: directory

- name: Create plist service file
  template:
    src: com.tarides.ocluster.worker.plist
    dest: "{{ ansible_env.HOME }}/Library/LaunchAgents/com.tarides.ocluster.worker.plist"

- name: Stop ocluster via launchctl
  shell: launchctl unload ~/Library/LaunchAgents/com.tarides.ocluster.worker.plist

- name: Download the source from GitHub
  git:
    repo: https://github.com/ocurrent/ocluster.git
    dest: "{{ ansible_env.HOME }}/ocluster"
    force: yes

- name: Checkout the correct SHA
  shell: git fetch origin master && git checkout 376d1fea0d832f9b0b1c947a0fc569cb870d3910 --recurse-submodules
  args: 
    chdir: "{{ ansible_env.HOME }}/ocluster"

- name: Checkout the correct SHA
  shell: git fetch origin master && git checkout 376d1fea0d832f9b0b1c947a0fc569cb870d3910 --recurse-submodules
  args: 
    chdir: "{{ ansible_env.HOME }}/ocluster/obuilder"

 - name: Add remote obuilder
   shell: git remote add mtelvers https://github.com/mtelvers/obuilder.git && git fetch --all
   args:
     chdir: "{{ ansible_env.HOME }}/ocluster/obuilder"

 - name: Checkout the correct SHA
   shell: git checkout 1b917744cb6959b889dcea3e68a586f4d5261d03
   args:
     chdir: "{{ ansible_env.HOME }}/ocluster/obuilder"

- name: Update Fetcher variable to User_temp
  replace:
    path: "{{ ansible_env.HOME }}/ocluster/worker/obuilder_build.ml"
    regexp: '^module Fetcher = Obuilder.Docker$'
    replace: 'module Fetcher = Obuilder.User_temp'

- name: Install Opam dependencies
  shell: eval $(opam env) && opam install . -y --confirm-level=unsafe-yes
  args:
    chdir: "{{ ansible_env.HOME }}/ocluster"

- name: Copy pool capability
  copy:
    src: "secrets/pool-macos-{{ ansible_architecture }}.cap"
    dest: "{{ ansible_env.HOME }}/pool-macos-{{ ansible_architecture }}.cap"
    mode: '0400'

- name: Ensure ~/lib exists
  file:
    path: "{{ ansible_env.HOME }}/lib"
    state: directory

- name: Start ocluster via launchctl
  shell: launchctl load ~/Library/LaunchAgents/com.tarides.ocluster.worker.plist

