---

- name: Create sudo file for admin group
  copy:
    dest: "/private/etc/sudoers.d/admin"
    content: |
      %admin ALL=(ALL) NOPASSWD: ALL
  become: yes

- name: Turn off Spotlight indexes for all volumes
  shell: mdutil -i off -d -a
  become: yes

- name: Unload Spotlight service
  shell: launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
  become: yes

- name: Turn off desktop icons for each mounted volume
  shell: defaults write com.apple.finder CreateDesktop -bool false
  become: yes

- name: Restart Finder
  shell: pkill Finder
  register: pkill
  failed_when: pkill.rc > 1

