
- name: Pause the worker
  shell: ci3-admin pause --wait macos-{{ ansible_architecture }} {{ inventory_hostname_short }}
  delegate_to: 127.0.0.1

- name: Reboot
  reboot:
  become: yes

- name: Unpause the worker
  shell: ci3-admin unpause macos-{{ ansible_architecture }} {{ inventory_hostname_short }}
  delegate_to: 127.0.0.1
