---

- name: Check if Homebrew is installed in {{ homebrew_prefix }}/bin/brew
  stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: homebrew_check

- name: Installing Homebrew
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:
    - not homebrew_check.stat.exists

- name: Add {{ homebrew_prefix }}/bin to the default system path
  copy:
    dest: "/private/etc/paths.d/homebrew"
    content: |
      {{ homebrew_prefix }}/bin
  become: yes
  when: homebrew_check.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name:
      - opam
      - pkg-config
    state: present
  register: result
  until: result is successful
  when:
    - not homebrew_check.stat.exists

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

