---

- name: Download the source from GitHub
  git:
    repo: https://github.com/ocurrent/macos-infra
    dest: "{{ ansible_env.HOME }}/macos-infra"
    force: yes

- name: chmod +x
  file:
    dest: "{{ ansible_env.HOME }}/macos-infra/scripts/{{ item }}"
    mode: a+x
  loop:
    - new-user.sh
    - macos-homebrew-ocaml.sh
    - cleanup.sh

- name: Create a scoreboard directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/scoreboard"
    state: directory
    mode: '0755'

- name: Check for user {{ user_name }}
  shell: dscl . read /Users/{{ user_name }}
  register: user_check
  failed_when: user_check.rc == -1

- name: Create user {{ user_name }}
  shell: "{{ ansible_env.HOME }}/macos-infra/scripts/new-user.sh 1000 {{ user_name }}"
  when: user_check.rc != 0

- name: Create sudo file for {{ user_name }}
  copy:
    dest: "/private/etc/sudoers.d/{{ user_name }}"
    content: |
      %{{ user_name }} ALL=(ALL) NOPASSWD: ALL
  become: yes

- name: Create a symbolic link
  file:
    src: /Users/{{ user_name }}
    dest: "{{ ansible_env.HOME }}/scoreboard/1000"
    state: link

- name: Create /Users/{{ user_name }}/local -- this should be created by new-user.sh
  file:
    path: /Users/{{ user_name }}/local
    state: directory
    mode: '0755'
    owner: "{{ user_name }}"
    group: admin
  become: yes

- name: Unmount /usr/local if it is mounted
  become: yes
  mount:
    path: /usr/local
    state: unmounted

- name: mount /usr/local
  become: yes
  shell: obuilderfs {{ ansible_env.HOME }}/scoreboard /usr/local -o allow_other

- name: Copy file setup script
  become: yes
  copy:
    #src: "{{ ansible_env.HOME }}/macos-infra/scripts/macos-homebrew-ocaml.sh"
    src: "{{ ansible_env.HOME }}/macos-homebrew-ocaml.sh"
    remote_src: yes
    dest: /Users/{{ user_name }}/macos-homebrew-ocaml.sh
    mode: u+rwx,g+rx,o+rx

- name: chown /Users/{{ user_name }} just to be sure
  become: yes
  file:
    dest: "/Users/{{ user_name }}"
    owner: "{{ user_name }}"
    group: admin
    recurse: yes

- name: Run macos-homebrew-ocaml.sh script as user {{ user_name }}
  become: yes
  become_user: "{{ user_name }}"
  shell: echo | ./macos-homebrew-ocaml.sh macos-homebrew-ocaml-4.14
  args:
    chdir: "/Users/{{ user_name }}"
    creates: "/Users/{{ user_name }}/opam-repository"

- name: Unmount /usr/local if it is mounted
  become: yes
  mount:
    path: /usr/local
    state: unmounted

- name: Delete user {{ user_name }}
  become: yes
  shell: dscl . -delete /Users/{{ user_name }}

- name: Remove /Users/macos-homebrew-ocaml-4.14
  become: yes
  file:
    state: absent
    path: /Users/macos-homebrew-ocaml-4.14

- name: Move /Users/{{ user_name }} to /Users/macos-homebrew-ocaml-4.14
  become: yes
  shell: "mv /Users/{{ user_name }} /Users/macos-homebrew-ocaml-4.14"
  args:
    removes: "/Users/{{ user_name }}"
    creates: "/Users/macos-homebrew-ocaml-4.14"

- name: Remove /Volumes/rsync
  become: yes
  file:
    state: absent
    path: /Volumes/rsync

