---

- name: Test for opam-sysinstall
  shell: eval $(opam env) && which opam-sysinstall
  register: which
  failed_when: which.rc == 2

- name: Pin opam-sysinstall
  shell: eval $(opam env) && opam pin add opam-sysinstall git+https://github.com/patricoferris/opam-sysinstall#mtelvers/main --yes
  when: which.rc != 0

- name: Opam System Compilers Directory
  file:
    path: /Volumes/ocaml
    state: directory
    mode: g+rwx
    group: admin
  become: yes

- name: "Install system compilers: {{ versions }}"
  shell: eval $(opam env) && opam exec -- opam sysinstall build --version="{{ versions }}" --prefix="/Volumes/ocaml" --jobs=6
  args:
    creates: "/Volumes/ocaml/4.14.0/bin/ocaml"

