---

- set_fact:
    short_version: "{{ version.split('.')[:2] | join('.') }}"

- name: Download the source from GitHub
  git:
    repo: https://github.com/ocurrent/macos-infra
    dest: "{{ ansible_env.HOME }}/macos-infra"
    force: yes

- name: chmod +x
  file:
    dest: "{{ ansible_env.HOME }}/macos-infra/scripts/{{ item }}"
    mode: a+x
  loop:
    - new-user.sh
    - macos-homebrew-ocaml.sh
    - cleanup.sh

- name: Check for user {{ user_name }}
  shell: dscl . read /Users/{{ user_name }}
  register: user_check
  failed_when: user_check.rc == -1

- name: Check for existing base image {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}
  shell: zfs list -H -o name {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}
  register: zfs_check
  failed_when: zfs_check.rc > 1

- name: Delete existing base image {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}
  shell: zfs destroy -R -r {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}
  when: zfs_check.rc == 0
  become: yes

- name: Unmount {{ homebrew_prefix }} if it is mounted
  become: yes
  mount:
    path: "{{ homebrew_prefix }}"
    state: unmounted

- name: Unmount /Users/{{ user_name }} if it is mounted
  become: yes
  mount:
    path: /Users/{{ user_name }}
    state: unmounted

- name: Remove any /Users/{{ user_name }}
  become: yes
  file:
    state: absent
    path: /Users/{{ user_name }}

- name: Delete user {{ user_name }} if it exists
  shell: dscl . -delete /Users/{{ user_name }}
  when: user_check.rc == 0
  become: yes

- name: Create user {{ user_name }}
  shell: "{{ ansible_env.HOME }}/macos-infra/scripts/new-user.sh 1000 {{ user_name }}"

- name: Create sudo file for {{ user_name }}
  copy:
    dest: "/private/etc/sudoers.d/{{ user_name }}"
    content: |
      {{ user_name }} ALL=(ALL) NOPASSWD: ALL
  become: yes

- name: Create ZFS volume for {{ homebrew_prefix }}
  become: yes
  shell: zfs create -p -o mountpoint={{ homebrew_prefix }} {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}/brew

- name: Create ZFS volume for /Users/{{ user_name }}
  become: yes
  shell: zfs create -p -o mountpoint=/Users/{{ user_name }} {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}/home

- name: Check for existing cache folder {{ zfs_pool }}/cache/c-opam-archives
  shell: zfs list -H -o name {{ zfs_pool }}/cache/c-opam-archives
  register: zfs_check
  failed_when: zfs_check.rc > 1

- name: Create cache folder {{ zfs_pool }}/cache/c-opam-archives
  shell: zfs create -p -o mountpoint=/Users/{{ user_name }}/.opam/download-cache {{ zfs_pool }}/cache/c-opam-archives
  when: zfs_check.rc == 1
  become: yes

- name: Mount cache folder {{ zfs_pool }}/cache/c-opam-archives
  shell: zfs set mountpoint=/Users/{{ user_name }}/.opam/download-cache {{ zfs_pool }}/cache/c-opam-archives
  when: zfs_check.rc == 0
  become: yes

- name: Check for existing cache folder {{ zfs_pool }}/cache/c-homebrew
  shell: zfs list -H -o name {{ zfs_pool }}/cache/c-homebrew
  register: zfs_check
  failed_when: zfs_check.rc > 1

- name: Create cache folder {{ zfs_pool }}/cache/c-homebrew
  shell: zfs create -p -o mountpoint=/Users/{{ user_name }}/Library/Caches/Homebrew {{ zfs_pool }}/cache/c-homebrew
  when: zfs_check.rc == 1
  become: yes

- name: Mount cache folder {{ zfs_pool }}/cache/c-homebrew
  shell: zfs set mountpoint=/Users/{{ user_name }}/Library/Caches/Homebrew {{ zfs_pool }}/cache/c-homebrew
  when: zfs_check.rc == 0
  become: yes

- name: Run chown on /Users/{{ user_name }}
  become: yes
  shell: chown -R {{ user_name }}:admin /Users/{{ user_name }}

- name: Copy file setup script
  become: yes
  copy:
    #src: "{{ ansible_env.HOME }}/macos-infra/scripts/macos-homebrew-ocaml.sh"
    #remote_src: yes
    src: "scripts/macos-homebrew-ocaml.sh"
    dest: /Users/{{ user_name }}/macos-homebrew-ocaml.sh
    mode: u+rwx,g+rx,o+rx

- name: Test
  become: yes
  become_user: "{{ user_name }}"
  shell: ls -l {{ homebrew_prefix }}
  args:
    chdir: "/Users/{{ user_name }}"

- name: Run macos-homebrew-ocaml.sh script as user {{ user_name }} for {{ short_version }}
  become: yes
  become_user: "{{ user_name }}"
  shell: ./macos-homebrew-ocaml.sh {{ version }}
  args:
    chdir: "/Users/{{ user_name }}"
    creates: "/Users/{{ user_name }}/opam-repository"

- name: Relocation ZFS cache volume {{ zfs_pool }}/cache/c-homebrew
  become: yes
  shell: zfs inherit mountpoint {{ zfs_pool }}/cache/c-homebrew

- name: Relocation ZFS cache volume {{ zfs_pool }}/cache/c-opam-archives
  become: yes
  shell: zfs inherit mountpoint {{ zfs_pool }}/cache/c-opam-archives

- name: Unmount ZFS volume for {{ homebrew_prefix }}
  become: yes
  shell: zfs set mountpoint=none {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}/brew

- name: Unmount ZFS volume for /Users/{{ user_name }}
  become: yes
  shell: zfs set mountpoint=none {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}/home

- name: Create a snapshot of the base image
  become: yes
  shell: zfs snapshot -r {{ zfs_pool }}/base-image/macos-homebrew-ocaml-{{ short_version }}@snap

- name: Delete user {{ user_name }}
  become: yes
  shell: dscl . -delete /Users/{{ user_name }}

